# Generated by Django 2.2.15 on 2020-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200811_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hfkhfjfhk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgjfhgjgjjhjgjg', models.BigIntegerField()),
            ],
        ),
    ]
